version: 2
jobs:
  deploy_prod:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repos
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
          working_directory: ~/repos/client
      - restore_cache: # 依存関係キャッシュを復元する特別なステップ
          # 依存関係キャッシュについては https://circleci.com/docs/ja/2.0/caching/ をお読みください
          key: dependency-cache-{{ checksum "./client/package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
          working_directory: ~/repos/client
      - save_cache: # 依存関係キャッシュを保存する特別なステップ
          key: dependency-cache-{{ checksum "./client/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: nuxt generate
          command: yarn nuxt generate
          working_directory: ~/repos/client
      - run:
          name: 'Install Heroku CLI, if necessary'
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: heroku maintenance on
          command: heroku maintenance:on --app ${HEROKU_APP_NAME}
      - run:
          name: Deploy to Heroku_Staging
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: heroku maintenance off
          command: heroku maintenance:off --app ${HEROKU_APP_NAME}

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_prod:
          filters:
            branches:
              only:
                - circleci
