version: 2
  jobs:
    build:
      docker:
        - image: circleci/golang:1.9
        - image: circleci/node:10.16.3
      working_directory: /go/src/github.com/zeno0119/golang-playground

      steps:
        - checkout
        - run: go get -u github.com/kardianos/govendor
        - run: govendor fetch +out
        - run: go build main.go
        - run: cd client
        - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

        - run: npm update npm

        - run: yarn install

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

          # run tests!
        - run: yarn nuxt generate

    deploy_prod:
      docker:
        - image: circleci/golang:1.9
      working_directory: /go/src/github.com/zeno0119/golang-playground
      steps:
        - checkout
        - run:
            name: 'Install Heroku CLI, if necessary'
            command: |
              if [[ $(command -v heroku) == "" ]]; then
                curl https://cli-assets.heroku.com/install.sh | sh
              else
                echo "Heroku is already installed. No operation was performed."
              fi
        - run:
            name: heroku maintenance on
            command: heroku maintenance:on --app ${HEROKU_APP_NAME_PROD}
        - run:
            name: Deploy to Heroku_Production
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git master
        - run:
            name: heroku maintenance off
            command: heroku maintenance:off --app ${HEROKU_APP_NAME_PROD}